baseURL = 'http://example.org/'
title = 'Christoph Völtzke'
theme = 'hugo-coder'
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params] # theme parameters
    author = "Christoph Völtzke"
    description = "Christoph Völtzkes personal website"
    info = "[Almost graduated Statistican]"
    
# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/christophvoe"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/christoph-v%C3%B6ltzke-31b925186/"
[[params.social]]
    name = "Mail me"
    weight = 3
    url = "mailto:voeltzke.christoph@gmail.com"
    
[[menu.main]]
    name = "About me"
    weight = 1
    url  = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "CV"
    weight = 3
    url = "/cv/"