baseURL = 'https://christophvoe.github.io/'
title = 'Christoph Völtzke'
theme = 'hugo-coder'
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params] # theme parameters
    author = "Christoph Völtzke"
    description = "Christoph Völtzkes personal website"
    info = "Graduate student - Data Scientist - Methodology & Statistics"
    avatarURL = "images/Profile_picture.png"
    
    colorScheme = "auto"
    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false
    
    favicon_16 = "/images/prof_ico_16x16.ico"
    favicon_32 = "/images/pfor_ico_32x32.ico"
    
[markup.goldmark.renderer]
    unsafe= true
    
# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/christophvoe"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/christoph-v%C3%B6ltzke-31b925186/"
[[params.social]]
    name = "Mail me"
    weight = 3
    url = "mailto:voeltzke.christoph@gmail.com"
    
[[menu.main]]
    name = "About me"
    weight = 1
    url  = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "CV"
    weight = 3
    url = "/docs/cv_sep.pdf"
[[menu.main]]
    name = "Consultation"
    weight = 4
    url  = "/consult/"